config/routes.rb
Point::Application.routes.draw do
  resources :computers
  resources :users
  resources :schools
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#home'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	helper_method :sort_column, :sort_direction

	def home
		@users = User.order("name" + " " + sort_direction)
		@schools = School.order("abbreviation" + " " + sort_direction)
	end

	private 
		
		def sort_column
			
		end

    	def sort_direction
    	  %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    	end
	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

	private
		def computer_count
			@school = School.find_by(id: current_user.school_id)
			@school.computers.count
		end
end

app/views/static_pages/_not_signed_in.html.erb
<h1 class="page-header">Welcome to Point!</h1>
	
<blockquote>Point was created with school based technical support specialists in mind. Use it to keep track of all computer assets at your school including useful data like room numbers and primary users. Contact your zone tech for access. Enjoy!</blockquote>

app/views/static_pages/_signed_in.html.erb
<% if !@schools.empty? %>
<h2>Welcome, <%= gravatar_for @current_user, 80 %> <%= current_user.name %></h2>
<div class="well">
	<p><strong>You currently work at:</strong> <%= user_school(@current_user) %><p>
	<p><strong>Your school has:</strong> <%= computer_count %> computers.</p>
</div>
<% else %>
	<div class="well">
		<p>There are no schools, contact the site administrator to report this error.</p>
	</div>
<% end %>

app/views/static_pages/home.html.erb
<% if signed_in? %>
	
	<%= render "signed_in" %>
	
	<% if admin? %>
		<% #TODO Show user school %>
		<h4>USERS | <%= link_to "Add", new_user_path %></span></h4>
		<%= render "users/users" %>
	
		<h4>SCHOOLS<span> | <%= link_to "Add", new_school_path %></span></h4>
		<%= render "schools/schools" %>

	<% end %>
	
	
<% else %>
	<%= render "not_signed_in" %>
<% end %>