config/routes.rb
Point::Application.routes.draw do
  resources :computers
  resources :users
  resources :schools
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#home'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/models/computer.rb
class Computer < ActiveRecord::Base
	belongs_to :school


	before_save { 
		self.servicetag = servicetag.upcase
		if self.bpinumber.empty?
			self.bpinumber = "none"
		end 
		}
	VALID_REGEX = { acps: /\A\d{6}\z/, bpi: /\A\d{6}\z/, room: /\d{2}[-]\d{3}\z/ }
	validates :acpsnumber, presence: true, format: { with: VALID_REGEX[:acps] }, uniqueness: { case_sensitive: false }
	validate :bpinumber, format: { with: VALID_REGEX[:bpi] }, uniqueness: { case_sensitive: false }, allow_blank: true, :if => :should_validate_bpi?
	validates :servicetag, presence: true, uniqueness: { case_sensitive: false }

	def should_validate_bpi?
		self.bpinumber == "none" ? false : true
	end
end

app/controllers/computers_controller.rb
class ComputersController < ApplicationController
  before_action :set_computer, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /computers
  # GET /computers.json
  helper_method :sort_column, :sort_direction
  def index
    if current_user.admin? && !hide_others?
      @computers = Computer.search(params[:search]).category(params[:category]).order(sort_column + " " + sort_direction)
    else
      @computers = Computer.where(school_id: current_user.school_id).search(params[:search]).category(params[:category]).order(sort_column + " " + sort_direction)
    end
  end

  # GET /computers/1
  # GET /computers/1.json
  def show
  end

  # GET /computers/new
  def new
    if current_user.admin?
      @computer = Computer.new
    else
      @school = School.find_by(id: current_user.school_id)
      @computer = @school.computers.new
    end
  end

  # GET /computers/1/edit
  def edit
  end

  def Computer.search(search)
    if search
      params = []
      values = {}
      unsearchableStr = ["id", "created_at", "updated_at", "school_id"]

      column_names.each do |c|
        unless unsearchableStr.include? c
          params << "lower(#{c}) LIKE :#{c}"
          values[c.to_sym] = search.downcase
        end
      end

      paramsStr = params.join (' OR ')
      where(paramsStr,values)
    else
      all
    end
  end

  # POST /computers
  # POST /computers.json
  def create
    if current_user.admin? 
      @computer = Computer.new(computer_params)
    else
      @school = School.find_by(id: current_user.school_id)
      @computer = @school.computers.new(computer_params)
    end

    respond_to do |format|
      if @computer.save
        format.html { redirect_to new_computer_path, notice: 'Computer was successfully created.' }
        format.json { render action: 'show', status: :created, location: computers_path }
      else
        format.html { render action: 'new' }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /computers/1
  # PATCH/PUT /computers/1.json
  def update
    respond_to do |format|
      if @computer.update(computer_params)
        format.html { redirect_to computers_path, notice: 'Computer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /computers/1
  # DELETE /computers/1.json
  def destroy
    @computer.destroy
    respond_to do |format|
      format.html { redirect_to computers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_computer
      @computer = Computer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def computer_params
      params.require(:computer).permit(:acpsnumber, :bpinumber, :make, :computer_model, :os, :room, :servicetag, :status, :school_id, :category, :username)
    end

    def correct_user
      @computer = Computer.find(params[:id])
      unless current_user.school_id == @computer.school_id or current_user.admin?
        redirect_to computers_url, notice: "That computer isn't at your school"
      end
    end

    def Computer.category(category_params)
      if category_params
        where(category: category_params)
      else 
        Computer.all
      end
    end

    def hide_others?
      current_user.setting_hide_others
    end

    def sort_column
      Computer.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/computers_helper.rb
module ComputersHelper
	
	def current_user
    	remember_token = User.encrypt(cookies[:remember_token])
    	@current_user ||= User.find_by(remember_token: remember_token)
 	 end

 	def computer_school(computer)
      school = School.find_by(id: computer.school_id)
      school_abbr = school.abbreviation
    end
end

app/views/computers/_computers.html.erb
<table id="computers" class="table table-striped">
  <% if current_page?('/') %>
    <thead>
      <tr>
        <th class="priority-4">School</th>
        <th class="priority-1">ACPS</th>
        <th class="priority-2">BPI</th>
        <th class="priority-4">Make</th>
        <th class="priority-3">Model</th>
        <th class="priority-2">OS</th>
        <th class="priority-2">Category</th>
        <th class="priority-1">Room</th>
        <th class="priority-2">Service Tag</th>
        <th class="priority-1">Status</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

  <% else %>
    <thead>
      <tr>
        <th class="priority-4"><%= sortable "school_id", "School" %></th>
        <th class="priority-1"><%= sortable "acpsnumber", "ACPS" %></th>
        <th class="priority-2"><%= sortable "bpinumber", "BPI" %></th>
        <th class="priority-4"><%= sortable "make" %></th>
        <th class="priority-3"><%= sortable "computer_model", "Model" %></th>
        <th class="priority-2"><%= sortable "os" %></th>
        <th class="priority-2"><%= sortable "category" %></th>
        <th class="priority-1"><%= sortable "room", "Room" %></th>
        <th class="priority-2"><%= sortable "servicetag", "Service Tag" %></th>
        <th class="priority-1"><%= sortable "status", "Status" %></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
  <% end %>

  <tbody>
    <% @computers.each do |computer| %>
      <tr>
        <td class="priority-4"><%= computer_school(computer) %></td>
        <td class="priority-1"><%= computer.acpsnumber %></td>
        <td class="priority-2"><%= computer.bpinumber %></td>
        <td class="priority-4"><%= computer.make %></td>
        <td class="priority-3"><%= computer.computer_model %></td>
        <td class="priority-2"><%= computer.os %></td>
        <td class="priority-2"><%= computer.category %></td>
        <td class="priority-1"><%= computer.room %></td>
        <td class="priority-2"><%= computer.servicetag %></td>
        <td class="priority-1"><%= computer.status %></td>
        <td><%= link_to 'Edit', edit_computer_path(computer) %></td>
        <td><%= link_to 'Destroy', computer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/computers/_form.html.erb
<%= form_for(@computer) do |f| %>
  
  <%= render "shared/error_messages", object: @computer %>
    
    <div class="form-group">
        <% if admin? %>
            <%= f.label :school_id, "School" %>
            <%= f.select :school_id, School.all.collect {|s| [s.abbreviation, s.id ] } %>
        <% end %>
        <%= f.label :room, "Room #" %>
        <%= f.text_field :room %>
        <%= f.label :category %>
        <%= f.select :category, options_for_select([ "Student", "Teacher", "Staff", "Lab", "Admin" ], f.object.category) %>
        <%= f.label :username %>
        <%= f.text_field :username %>
        <%= f.label :acpsnumber, "ACPS Number" %>
        <%= f.text_field :acpsnumber %>
        <%= f.label :bpinumber, "BPI" %>
        <%= f.text_field :bpinumber %>
    </div>
    
    <div class="form-group">
        <%= f.label :servicetag, "Service Tag" %>
        <%= f.text_field :servicetag %>
        <%= f.label :make, "Make" %>
        <%= f.select :make, options_for_select([["Apple", "Apple"], ["Dell", "Dell"]], f.object.make) %>
        
        <!-- Dynamic Form - Apple -->
        <div id="Apple" class="model_form">
            <%= f.label :computer_model, "Model" %>
            <%= f.select :computer_model, 
                            options_for_select([ "eMac", "iMac", "MacBook"], f.object.computer_model) %>
            <%= f.label :os, "OS" %>
            <%= f.select :os,
                            options_for_select([ "10.5 Leopard", "10.6 Snow Leopard", "10.7 Lion", "10.8 Mountain Lion", "10.9 Mavericks"], f.object.os) %>
        </div>
        
        <!-- Dynamic Form - Dell -->
        <div id="Dell" class="model_form">
            <%= f.label :computer_model, "Model" %>
            <%= f.select :computer_model, 
                            options_for_select([ "Optiplex GX520", "Optiplex GX620", "Optiplex 740", "Optiplex 745", "Optiplex 755", "Optiplex 760", "Optiplex 780", "Optiplex 790", "Optiplex 7010", "Latitude 6430"], f.object.computer_model) %>
            <%= f.label :os, "OS" %>
            <%= f.select :os, options_for_select([ "Windows XP", "Windows Server 2000", "Windows 7"], f.object.os) %>
        </div>
        <%= f.label :status %>
        <%= f.select :status, options_for_select([ "Active", "Inactive", "Repair", "Surplus" ], f.object.status) %>
    </div>

    <!-- Submit Button -->
    <div class="form-group">
        <%= f.submit "Save Computer", class: "btn btn-primary" %>
    </div>

<% end %>

app/views/computers/admin.html.erb
<h4>
  <strong>LISTING ADMIN COMPUTERS</strong>
</h4>
<%= render 'computers' %>

app/views/computers/edit.html.erb
<%= link_to 'Back', computers_path %>
<h4><strong>EDIT COMPUTER</strong></h4>
<div>
	<%= render 'form' %>
</div>

app/views/computers/index.html.erb
<h4>
  <strong>Listing <%= params[:category] %> Computers</strong>
</h4>
	<%= render 'computers' %>

app/views/computers/lab.html.erb
<h4>
  <strong>LISTING LAB COMPUTERS</strong>
</h4>
<%= render 'computers' %>

app/views/computers/new.html.erb
<% provide(:title, "Add Computer") %>
<%= link_to 'Back', computers_path %>
<h4><strong>NEW COMPUTER</strong></h4>
<div>
		<%= render 'form' %>
</div>

app/views/computers/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_computer_path(@computer) %> |
<%= link_to 'Back', computers_path %>

<p>
  <strong>School:</strong>
  <%= @computer.school %>
</p>
<p>
  <strong>ACPS Number:</strong>
  <%= @computer.acpsnumber %>
</p>

<p>
  <strong>BPI:</strong>
  <%= @computer.bpinumber %>
</p>

<p>
  <strong>Make:</strong>
  <%= @computer.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @computer.computer_model %>
</p>

<p>
  <strong>OS:</strong>
  <%= @computer.os %>
</p>

<p>
  <strong>Room #:</strong>
  <%= @computer.room %>
</p>

<p>
  <strong>Status:</strong>
  <%= @computer.status %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @computer.comment %>
</p>

app/views/computers/student.html.erb
<h4>
  <strong>LISTING STUDENT COMPUTERS</strong>
</h4>
<%= render 'computers' %>

app/views/computers/teacher.html.erb
<h4>
  <strong>LISTING TEACHER COMPUTERS</strong>
</h4>
<%= render 'computers' %>