config/routes.rb
Point::Application.routes.draw do
  resources :computers
  resources :users
  resources :schools
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#home'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/models/school.rb
class School < ActiveRecord::Base
	has_many :computers, dependent: :destroy
	has_many :users, dependent: :destroy

	before_save { self.abbreviation = abbreviation.upcase }
	validates :abbreviation, presence: true
	validates :code, presence: true
	validates :name, presence: true
	validates :phone, presence: true
	validates :address, presence: true
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
	before_action :signed_in_user
	before_action :admin_user, only:[:new, :create, :destroy, :edit, :update]

	helper_method :sort_column, :sort_direction
	
	def index
		@schools = School.order(sort_column + " " + sort_direction)
	end

	def create
		@school = School.new(school_params)
		if @school.save
			redirect_to root_url
			flash[:success] = "School Created"
		else
			render "new"
		end
	end

	def update
		@school = School.find(params[:id])
		if @school.update_attributes(school_params)
     		flash[:success] = "School Updated"
     		redirect_to root_url
     	else 
     		render "edit"
		end
	end

	def destroy
	end

	def new
		@school = School.new
	end

	def edit
		@school = School.find(params[:id])
	end

	private 

		def school_params
			params.require(:school).permit(:abbreviation, :code, :name, :phone, :address)
		end

		def sort_column
  			Computer.column_names.include?(params[:sort]) ? params[:sort] : "id"
  		end

  		def sort_direction
  			%w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  		end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <%= render "shared/error_messages", object: @school %>
    <div class="form-group">
    <%= f.label :abbreviation, "Short" %>
    <%= f.text_field :abbreviation %>
    <%= f.label :code, "Code" %>
    <%= f.text_field :code %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
    <%= f.label :phone, "Phone" %>
    <%= f.text_field :phone %>
    <%= f.label :address, "Address" %>
    <%= f.text_field :address %>
    </div>
    <div class="form-group">
    <%= f.submit "Save School", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/schools/_schools.html.erb
<table id="schools" class="table table-striped">
 <% if current_page?('/') %>
    <thead>
      <tr>
        <th>Short</th>
        <th>Code</th>
        <th>Name</th>
        <th>Phone</th>
        <th>Address</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

  <% else %>
   <thead>
     <tr>
       <th><%= sortable "abbreviation", "Short" %></th>
       <th><%= sortable "code" %></th>
       <th><%= sortable "name" %></th>
       <th><%= sortable "phone" %></th>
       <th><%= sortable "address" %></th>
       <th></th>
       <th></th>
     </tr>
   </thead>
  <% end %>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.abbreviation %></td>
        <td><%= school.code %></td>
        <td><%= school.name %></td>
        <td><%= school.phone %></td>
        <td><%= school.address %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/schools/edit.html.erb
<% provide(:title, "Edit School") %>
<%= link_to 'Back', schools_path %>
<h4><strong>EDIT SCHOOL</strong></h4>
<div>
		<%= render 'form' %>
</div>

app/views/schools/index.html.erb
<h4>
  <strong>LISTING ALL SCHOOLS</strong>
</h4>
	<%= render 'schools' %>

app/views/schools/new.html.erb
<% provide(:title, "Add School") %>
<%= link_to 'Back', schools_path %>
<h4><strong>NEW SCHOOL</strong></h4>
<div>
		<%= render 'form' %>
</div>