config/routes.rb
Point::Application.routes.draw do
  resources :computers
  resources :users
  resources :schools
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#home'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/views/layouts/_display.html.erb
  <div class="display">
    <div>
        <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
    		<%= yield %>
        <%= debug(params) if Rails.env.development? %>
    </div>
  </div>

app/views/layouts/_sidebar.html.erb
<aside class="control-panel">
    <section class="sidebar-header clearfix">
        <a href="/" class="brand">point</a>
        <section id="search-bar">
        <%= form_tag computers_path, method: "get" do %>
            <%= hidden_field_tag :direction, params[:direction] %>  
            <%= hidden_field_tag :sort, params[:sort] %>
            <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Go", name: nil, class: "btn btn-primary" %>
        <% end %>
        </section>
        <span>
            <% if signed_in? %>
                <%= gravatar_for(current_user, 20) %>
                <%= link_to "Settings", edit_user_path(current_user) %> | 
                <%= link_to "Sign Out", signout_path, method: "delete" %>
            <% else %>
                <%= link_to "Sign In", signin_path %>
            <% end %>
        </span>
    </section>
    <section class="menu-btn" id="menu-btn">&#8801; Menu</section>
    <nav class="clearfix menu">
        <ul>
    	    <li><%= link_to 'Add', new_computer_path, class: current(controller: 'computers', action: 'new')  %></li>
    	    <li><%= link_to 'All', '/computers', class: current(controller: 'computers', action: 'index', category: '*') %></li>

            <li><%= link_to 'Student', 
                   computers_path(category: 'Student'), 
                   class: current(category: 'Student') %>
            </li>
            <li><%= link_to 'Teacher', 
                   computers_path(category: 'Teacher'), 
                   class: current(category: 'Teacher') %>
            </li>
            <li><%= link_to 'Staff', 
                   computers_path(category: 'Staff'), 
                   class: current(category: 'Staff') %>
            </li>
            <li><%= link_to 'Lab', 
                   computers_path(category: 'Lab'), 
                   class: current(category: 'Lab') %>
            </li>
            <li><%= link_to 'Admin', 
                   computers_path(category: 'Admin'), 
                   class: current(category: 'Admin') %>
            </li>

        </ul>
    </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="wrap">
  <%= render "layouts/sidebar" %>
  <%= render "layouts/display" %>
 </div>
</body>
</html>